package com.mybatis.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AsesoriasExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public AsesoriasExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdAsesoriaIsNull() {
			addCriterion("id_asesoria is null");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaIsNotNull() {
			addCriterion("id_asesoria is not null");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaEqualTo(Integer value) {
			addCriterion("id_asesoria =", value, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaNotEqualTo(Integer value) {
			addCriterion("id_asesoria <>", value, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaGreaterThan(Integer value) {
			addCriterion("id_asesoria >", value, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_asesoria >=", value, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaLessThan(Integer value) {
			addCriterion("id_asesoria <", value, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaLessThanOrEqualTo(Integer value) {
			addCriterion("id_asesoria <=", value, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaIn(List<Integer> values) {
			addCriterion("id_asesoria in", values, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaNotIn(List<Integer> values) {
			addCriterion("id_asesoria not in", values, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaBetween(Integer value1, Integer value2) {
			addCriterion("id_asesoria between", value1, value2, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdAsesoriaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_asesoria not between", value1, value2, "idAsesoria");
			return (Criteria) this;
		}

		public Criteria andIdEquipoIsNull() {
			addCriterion("id_equipo is null");
			return (Criteria) this;
		}

		public Criteria andIdEquipoIsNotNull() {
			addCriterion("id_equipo is not null");
			return (Criteria) this;
		}

		public Criteria andIdEquipoEqualTo(Integer value) {
			addCriterion("id_equipo =", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoNotEqualTo(Integer value) {
			addCriterion("id_equipo <>", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoGreaterThan(Integer value) {
			addCriterion("id_equipo >", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_equipo >=", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoLessThan(Integer value) {
			addCriterion("id_equipo <", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoLessThanOrEqualTo(Integer value) {
			addCriterion("id_equipo <=", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoIn(List<Integer> values) {
			addCriterion("id_equipo in", values, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoNotIn(List<Integer> values) {
			addCriterion("id_equipo not in", values, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoBetween(Integer value1, Integer value2) {
			addCriterion("id_equipo between", value1, value2, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_equipo not between", value1, value2, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdAsesorIsNull() {
			addCriterion("id_asesor is null");
			return (Criteria) this;
		}

		public Criteria andIdAsesorIsNotNull() {
			addCriterion("id_asesor is not null");
			return (Criteria) this;
		}

		public Criteria andIdAsesorEqualTo(Integer value) {
			addCriterion("id_asesor =", value, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorNotEqualTo(Integer value) {
			addCriterion("id_asesor <>", value, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorGreaterThan(Integer value) {
			addCriterion("id_asesor >", value, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_asesor >=", value, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorLessThan(Integer value) {
			addCriterion("id_asesor <", value, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorLessThanOrEqualTo(Integer value) {
			addCriterion("id_asesor <=", value, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorIn(List<Integer> values) {
			addCriterion("id_asesor in", values, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorNotIn(List<Integer> values) {
			addCriterion("id_asesor not in", values, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorBetween(Integer value1, Integer value2) {
			addCriterion("id_asesor between", value1, value2, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andIdAsesorNotBetween(Integer value1, Integer value2) {
			addCriterion("id_asesor not between", value1, value2, "idAsesor");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaIsNull() {
			addCriterion("dia_semana is null");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaIsNotNull() {
			addCriterion("dia_semana is not null");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaEqualTo(Integer value) {
			addCriterion("dia_semana =", value, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaNotEqualTo(Integer value) {
			addCriterion("dia_semana <>", value, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaGreaterThan(Integer value) {
			addCriterion("dia_semana >", value, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaGreaterThanOrEqualTo(Integer value) {
			addCriterion("dia_semana >=", value, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaLessThan(Integer value) {
			addCriterion("dia_semana <", value, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaLessThanOrEqualTo(Integer value) {
			addCriterion("dia_semana <=", value, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaIn(List<Integer> values) {
			addCriterion("dia_semana in", values, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaNotIn(List<Integer> values) {
			addCriterion("dia_semana not in", values, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaBetween(Integer value1, Integer value2) {
			addCriterion("dia_semana between", value1, value2, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andDiaSemanaNotBetween(Integer value1, Integer value2) {
			addCriterion("dia_semana not between", value1, value2, "diaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaIsNull() {
			addCriterion("hora_semana is null");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaIsNotNull() {
			addCriterion("hora_semana is not null");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaEqualTo(Integer value) {
			addCriterion("hora_semana =", value, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaNotEqualTo(Integer value) {
			addCriterion("hora_semana <>", value, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaGreaterThan(Integer value) {
			addCriterion("hora_semana >", value, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaGreaterThanOrEqualTo(Integer value) {
			addCriterion("hora_semana >=", value, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaLessThan(Integer value) {
			addCriterion("hora_semana <", value, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaLessThanOrEqualTo(Integer value) {
			addCriterion("hora_semana <=", value, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaIn(List<Integer> values) {
			addCriterion("hora_semana in", values, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaNotIn(List<Integer> values) {
			addCriterion("hora_semana not in", values, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaBetween(Integer value1, Integer value2) {
			addCriterion("hora_semana between", value1, value2, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andHoraSemanaNotBetween(Integer value1, Integer value2) {
			addCriterion("hora_semana not between", value1, value2, "horaSemana");
			return (Criteria) this;
		}

		public Criteria andIdSemestreIsNull() {
			addCriterion("id_semestre is null");
			return (Criteria) this;
		}

		public Criteria andIdSemestreIsNotNull() {
			addCriterion("id_semestre is not null");
			return (Criteria) this;
		}

		public Criteria andIdSemestreEqualTo(Integer value) {
			addCriterion("id_semestre =", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreNotEqualTo(Integer value) {
			addCriterion("id_semestre <>", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreGreaterThan(Integer value) {
			addCriterion("id_semestre >", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_semestre >=", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreLessThan(Integer value) {
			addCriterion("id_semestre <", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreLessThanOrEqualTo(Integer value) {
			addCriterion("id_semestre <=", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreIn(List<Integer> values) {
			addCriterion("id_semestre in", values, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreNotIn(List<Integer> values) {
			addCriterion("id_semestre not in", values, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreBetween(Integer value1, Integer value2) {
			addCriterion("id_semestre between", value1, value2, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreNotBetween(Integer value1, Integer value2) {
			addCriterion("id_semestre not between", value1, value2, "idSemestre");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table asesorias
	 * @mbg.generated  Sun Apr 22 21:01:29 COT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asesorias
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 26 14:44:13 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}