package com.mybatis.models;

import java.util.Date;

public class Asesorias {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asesorias.id_asesoria
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	private Integer idAsesoria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asesorias.id_equipo
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	private Integer idEquipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asesorias.id_asesor
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	private Integer idAsesor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asesorias.dia_semana
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	private Integer diaSemana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asesorias.hora_semana
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	private Date horaSemana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asesorias.estado
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	private Boolean estado;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asesorias.id_asesoria
	 * @return  the value of asesorias.id_asesoria
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public Integer getIdAsesoria() {
		return idAsesoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asesorias.id_asesoria
	 * @param idAsesoria  the value for asesorias.id_asesoria
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public void setIdAsesoria(Integer idAsesoria) {
		this.idAsesoria = idAsesoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asesorias.id_equipo
	 * @return  the value of asesorias.id_equipo
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public Integer getIdEquipo() {
		return idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asesorias.id_equipo
	 * @param idEquipo  the value for asesorias.id_equipo
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asesorias.id_asesor
	 * @return  the value of asesorias.id_asesor
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public Integer getIdAsesor() {
		return idAsesor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asesorias.id_asesor
	 * @param idAsesor  the value for asesorias.id_asesor
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public void setIdAsesor(Integer idAsesor) {
		this.idAsesor = idAsesor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asesorias.dia_semana
	 * @return  the value of asesorias.dia_semana
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public Integer getDiaSemana() {
		return diaSemana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asesorias.dia_semana
	 * @param diaSemana  the value for asesorias.dia_semana
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public void setDiaSemana(Integer diaSemana) {
		this.diaSemana = diaSemana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asesorias.hora_semana
	 * @return  the value of asesorias.hora_semana
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public Date getHoraSemana() {
		return horaSemana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asesorias.hora_semana
	 * @param horaSemana  the value for asesorias.hora_semana
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public void setHoraSemana(Date horaSemana) {
		this.horaSemana = horaSemana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asesorias.estado
	 * @return  the value of asesorias.estado
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public Boolean getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asesorias.estado
	 * @param estado  the value for asesorias.estado
	 * @mbg.generated  Mon Mar 26 14:45:33 COT 2018
	 */
	public void setEstado(Boolean estado) {
		this.estado = estado;
	}
}