package com.mybatis.models;

public class Asignatura {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asignatura.id_asignatura
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	private Integer idAsignatura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asignatura.codigo
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	private String codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asignatura.nombre
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asignatura.semestre
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	private Integer semestre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asignatura.id_asignatura
	 * @return  the value of asignatura.id_asignatura
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public Integer getIdAsignatura() {
		return idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asignatura.id_asignatura
	 * @param idAsignatura  the value for asignatura.id_asignatura
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public void setIdAsignatura(Integer idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asignatura.codigo
	 * @return  the value of asignatura.codigo
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asignatura.codigo
	 * @param codigo  the value for asignatura.codigo
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asignatura.nombre
	 * @return  the value of asignatura.nombre
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asignatura.nombre
	 * @param nombre  the value for asignatura.nombre
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asignatura.semestre
	 * @return  the value of asignatura.semestre
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public Integer getSemestre() {
		return semestre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asignatura.semestre
	 * @param semestre  the value for asignatura.semestre
	 * @mbg.generated  Sun Mar 25 12:58:07 COT 2018
	 */
	public void setSemestre(Integer semestre) {
		this.semestre = semestre;
	}

}