package com.mybatis.models;

public class Bonificacion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonificacion.id_bonificacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    private Integer idBonificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonificacion.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    private Integer idSocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonificacion.id_tipo_bonificacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    private Integer idTipoBonificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonificacion.id_equipo
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    private Integer idEquipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonificacion.id_bonificacion
     *
     * @return the value of bonificacion.id_bonificacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public Integer getIdBonificacion() {
        return idBonificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonificacion.id_bonificacion
     *
     * @param idBonificacion the value for bonificacion.id_bonificacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public void setIdBonificacion(Integer idBonificacion) {
        this.idBonificacion = idBonificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonificacion.id_socializacion
     *
     * @return the value of bonificacion.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public Integer getIdSocializacion() {
        return idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonificacion.id_socializacion
     *
     * @param idSocializacion the value for bonificacion.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public void setIdSocializacion(Integer idSocializacion) {
        this.idSocializacion = idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonificacion.id_tipo_bonificacion
     *
     * @return the value of bonificacion.id_tipo_bonificacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public Integer getIdTipoBonificacion() {
        return idTipoBonificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonificacion.id_tipo_bonificacion
     *
     * @param idTipoBonificacion the value for bonificacion.id_tipo_bonificacion
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public void setIdTipoBonificacion(Integer idTipoBonificacion) {
        this.idTipoBonificacion = idTipoBonificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonificacion.id_equipo
     *
     * @return the value of bonificacion.id_equipo
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public Integer getIdEquipo() {
        return idEquipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonificacion.id_equipo
     *
     * @param idEquipo the value for bonificacion.id_equipo
     *
     * @mbg.generated Mon Mar 26 14:46:04 COT 2018
     */
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
}