package com.mybatis.models;

public class Califxsoc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column califxsoc.id_califxsoc
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	private Integer idCalifxsoc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column califxsoc.id_calificador
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	private Integer idCalificador;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column califxsoc.observaciones
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	private String observaciones;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column califxsoc.id_salonxequipo
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	private Integer idSalonxequipo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column califxsoc.id_califxsoc
	 * @return  the value of califxsoc.id_califxsoc
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public Integer getIdCalifxsoc() {
		return idCalifxsoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column califxsoc.id_califxsoc
	 * @param idCalifxsoc  the value for califxsoc.id_califxsoc
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public void setIdCalifxsoc(Integer idCalifxsoc) {
		this.idCalifxsoc = idCalifxsoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column califxsoc.id_calificador
	 * @return  the value of califxsoc.id_calificador
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public Integer getIdCalificador() {
		return idCalificador;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column califxsoc.id_calificador
	 * @param idCalificador  the value for califxsoc.id_calificador
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public void setIdCalificador(Integer idCalificador) {
		this.idCalificador = idCalificador;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column califxsoc.observaciones
	 * @return  the value of califxsoc.observaciones
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public String getObservaciones() {
		return observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column califxsoc.observaciones
	 * @param observaciones  the value for califxsoc.observaciones
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column califxsoc.id_salonxequipo
	 * @return  the value of califxsoc.id_salonxequipo
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public Integer getIdSalonxequipo() {
		return idSalonxequipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column califxsoc.id_salonxequipo
	 * @param idSalonxequipo  the value for califxsoc.id_salonxequipo
	 * @mbg.generated  Mon Jun 11 00:27:45 COT 2018
	 */
	public void setIdSalonxequipo(Integer idSalonxequipo) {
		this.idSalonxequipo = idSalonxequipo;
	}
}