package com.mybatis.models;

public class Cargo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo.id_cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	private Integer idCargo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo.descripcion
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo.id_cargo
	 * @return  the value of cargo.id_cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	public Integer getIdCargo() {
		return idCargo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo.id_cargo
	 * @param idCargo  the value for cargo.id_cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	public void setIdCargo(Integer idCargo) {
		this.idCargo = idCargo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo.descripcion
	 * @return  the value of cargo.descripcion
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo.descripcion
	 * @param descripcion  the value for cargo.descripcion
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}