package com.mybatis.models;

public class Cuadrante {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cuadrante.id_cuadrante
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	private Integer idCuadrante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cuadrante.numero
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	private Integer numero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cuadrante.descripcion
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	private String descripcion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cuadrante.id_asignatura
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	private Integer idAsignatura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cuadrante.id_semestre
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	private Integer idSemestre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cuadrante.nombre
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cuadrante.id_cuadrante
	 * @return  the value of cuadrante.id_cuadrante
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public Integer getIdCuadrante() {
		return idCuadrante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cuadrante.id_cuadrante
	 * @param idCuadrante  the value for cuadrante.id_cuadrante
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public void setIdCuadrante(Integer idCuadrante) {
		this.idCuadrante = idCuadrante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cuadrante.numero
	 * @return  the value of cuadrante.numero
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public Integer getNumero() {
		return numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cuadrante.numero
	 * @param numero  the value for cuadrante.numero
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cuadrante.descripcion
	 * @return  the value of cuadrante.descripcion
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cuadrante.descripcion
	 * @param descripcion  the value for cuadrante.descripcion
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cuadrante.id_asignatura
	 * @return  the value of cuadrante.id_asignatura
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public Integer getIdAsignatura() {
		return idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cuadrante.id_asignatura
	 * @param idAsignatura  the value for cuadrante.id_asignatura
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public void setIdAsignatura(Integer idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cuadrante.id_semestre
	 * @return  the value of cuadrante.id_semestre
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public Integer getIdSemestre() {
		return idSemestre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cuadrante.id_semestre
	 * @param idSemestre  the value for cuadrante.id_semestre
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public void setIdSemestre(Integer idSemestre) {
		this.idSemestre = idSemestre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cuadrante.nombre
	 * @return  the value of cuadrante.nombre
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cuadrante.nombre
	 * @param nombre  the value for cuadrante.nombre
	 * @mbg.generated  Mon Mar 26 12:48:07 COT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}