package com.mybatis.models;

import java.util.ArrayList;
import java.util.List;

public class EquipoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public EquipoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdEquipoIsNull() {
			addCriterion("id_equipo is null");
			return (Criteria) this;
		}

		public Criteria andIdEquipoIsNotNull() {
			addCriterion("id_equipo is not null");
			return (Criteria) this;
		}

		public Criteria andIdEquipoEqualTo(Integer value) {
			addCriterion("id_equipo =", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoNotEqualTo(Integer value) {
			addCriterion("id_equipo <>", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoGreaterThan(Integer value) {
			addCriterion("id_equipo >", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_equipo >=", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoLessThan(Integer value) {
			addCriterion("id_equipo <", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoLessThanOrEqualTo(Integer value) {
			addCriterion("id_equipo <=", value, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoIn(List<Integer> values) {
			addCriterion("id_equipo in", values, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoNotIn(List<Integer> values) {
			addCriterion("id_equipo not in", values, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoBetween(Integer value1, Integer value2) {
			addCriterion("id_equipo between", value1, value2, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andIdEquipoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_equipo not between", value1, value2, "idEquipo");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreIsNull() {
			addCriterion("id_semestre is null");
			return (Criteria) this;
		}

		public Criteria andIdSemestreIsNotNull() {
			addCriterion("id_semestre is not null");
			return (Criteria) this;
		}

		public Criteria andIdSemestreEqualTo(Integer value) {
			addCriterion("id_semestre =", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreNotEqualTo(Integer value) {
			addCriterion("id_semestre <>", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreGreaterThan(Integer value) {
			addCriterion("id_semestre >", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_semestre >=", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreLessThan(Integer value) {
			addCriterion("id_semestre <", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreLessThanOrEqualTo(Integer value) {
			addCriterion("id_semestre <=", value, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreIn(List<Integer> values) {
			addCriterion("id_semestre in", values, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreNotIn(List<Integer> values) {
			addCriterion("id_semestre not in", values, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreBetween(Integer value1, Integer value2) {
			addCriterion("id_semestre between", value1, value2, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdSemestreNotBetween(Integer value1, Integer value2) {
			addCriterion("id_semestre not between", value1, value2, "idSemestre");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaIsNull() {
			addCriterion("id_asignatura is null");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaIsNotNull() {
			addCriterion("id_asignatura is not null");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaEqualTo(Integer value) {
			addCriterion("id_asignatura =", value, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaNotEqualTo(Integer value) {
			addCriterion("id_asignatura <>", value, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaGreaterThan(Integer value) {
			addCriterion("id_asignatura >", value, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_asignatura >=", value, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaLessThan(Integer value) {
			addCriterion("id_asignatura <", value, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaLessThanOrEqualTo(Integer value) {
			addCriterion("id_asignatura <=", value, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaIn(List<Integer> values) {
			addCriterion("id_asignatura in", values, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaNotIn(List<Integer> values) {
			addCriterion("id_asignatura not in", values, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaBetween(Integer value1, Integer value2) {
			addCriterion("id_asignatura between", value1, value2, "idAsignatura");
			return (Criteria) this;
		}

		public Criteria andIdAsignaturaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_asignatura not between", value1, value2, "idAsignatura");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table equipo
	 * @mbg.generated  Sun Apr 01 21:24:44 COT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table equipo
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 04 00:51:48 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}