package com.mybatis.models;

public class Equipo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipo.id_equipo
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	private Integer idEquipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipo.codigo
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipo.nombre
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipo.id_semestre
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	private Integer idSemestre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipo.id_asignatura
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	private Integer idAsignatura;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipo.id_equipo
	 * @return  the value of equipo.id_equipo
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public Integer getIdEquipo() {
		return idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipo.id_equipo
	 * @param idEquipo  the value for equipo.id_equipo
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipo.codigo
	 * @return  the value of equipo.codigo
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipo.codigo
	 * @param codigo  the value for equipo.codigo
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipo.nombre
	 * @return  the value of equipo.nombre
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipo.nombre
	 * @param nombre  the value for equipo.nombre
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipo.id_semestre
	 * @return  the value of equipo.id_semestre
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public Integer getIdSemestre() {
		return idSemestre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipo.id_semestre
	 * @param idSemestre  the value for equipo.id_semestre
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public void setIdSemestre(Integer idSemestre) {
		this.idSemestre = idSemestre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipo.id_asignatura
	 * @return  the value of equipo.id_asignatura
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public Integer getIdAsignatura() {
		return idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipo.id_asignatura
	 * @param idAsignatura  the value for equipo.id_asignatura
	 * @mbg.generated  Sat May 05 22:11:04 COT 2018
	 */
	public void setIdAsignatura(Integer idAsignatura) {
		this.idAsignatura = idAsignatura;
	}
}