package com.mybatis.models;

public class Estudiantesxequipos {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.id_estxequip
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	private Integer idEstxequip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.id_estudiante
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	private Integer idEstudiante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.id_equipo
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	private Integer idEquipo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.id_estxequip
	 * @return  the value of estudiantesxequipos.id_estxequip
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	public Integer getIdEstxequip() {
		return idEstxequip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.id_estxequip
	 * @param idEstxequip  the value for estudiantesxequipos.id_estxequip
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	public void setIdEstxequip(Integer idEstxequip) {
		this.idEstxequip = idEstxequip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.id_estudiante
	 * @return  the value of estudiantesxequipos.id_estudiante
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	public Integer getIdEstudiante() {
		return idEstudiante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.id_estudiante
	 * @param idEstudiante  the value for estudiantesxequipos.id_estudiante
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	public void setIdEstudiante(Integer idEstudiante) {
		this.idEstudiante = idEstudiante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.id_equipo
	 * @return  the value of estudiantesxequipos.id_equipo
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	public Integer getIdEquipo() {
		return idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.id_equipo
	 * @param idEquipo  the value for estudiantesxequipos.id_equipo
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}
}