package com.mybatis.models;

public class Estudiantesxequipos {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.id_estxequip
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	private Integer idEstxequip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.id_estudiante
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	private Integer idEstudiante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.id_equipo
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	private Integer idEquipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column estudiantesxequipos.nombre
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.id_estxequip
	 * @return  the value of estudiantesxequipos.id_estxequip
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public Integer getIdEstxequip() {
		return idEstxequip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.id_estxequip
	 * @param idEstxequip  the value for estudiantesxequipos.id_estxequip
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public void setIdEstxequip(Integer idEstxequip) {
		this.idEstxequip = idEstxequip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.id_estudiante
	 * @return  the value of estudiantesxequipos.id_estudiante
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public Integer getIdEstudiante() {
		return idEstudiante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.id_estudiante
	 * @param idEstudiante  the value for estudiantesxequipos.id_estudiante
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public void setIdEstudiante(Integer idEstudiante) {
		this.idEstudiante = idEstudiante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.id_equipo
	 * @return  the value of estudiantesxequipos.id_equipo
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public Integer getIdEquipo() {
		return idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.id_equipo
	 * @param idEquipo  the value for estudiantesxequipos.id_equipo
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column estudiantesxequipos.nombre
	 * @return  the value of estudiantesxequipos.nombre
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column estudiantesxequipos.nombre
	 * @param nombre  the value for estudiantesxequipos.nombre
	 * @mbg.generated  Mon Dec 04 04:05:06 COT 2017
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}