package com.mybatis.models;

public class Notasxcalifxsoc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notasxcalifxsoc.id_notaxsocializacion
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    private Integer idNotaxsocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notasxcalifxsoc.id_califxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    private Integer idCalifxsoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notasxcalifxsoc.id_rubricaxitem
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    private Integer idRubricaxitem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notasxcalifxsoc.id_notaxsocializacion
     *
     * @return the value of notasxcalifxsoc.id_notaxsocializacion
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    public Integer getIdNotaxsocializacion() {
        return idNotaxsocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notasxcalifxsoc.id_notaxsocializacion
     *
     * @param idNotaxsocializacion the value for notasxcalifxsoc.id_notaxsocializacion
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    public void setIdNotaxsocializacion(Integer idNotaxsocializacion) {
        this.idNotaxsocializacion = idNotaxsocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notasxcalifxsoc.id_califxsoc
     *
     * @return the value of notasxcalifxsoc.id_califxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    public Integer getIdCalifxsoc() {
        return idCalifxsoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notasxcalifxsoc.id_califxsoc
     *
     * @param idCalifxsoc the value for notasxcalifxsoc.id_califxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    public void setIdCalifxsoc(Integer idCalifxsoc) {
        this.idCalifxsoc = idCalifxsoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notasxcalifxsoc.id_rubricaxitem
     *
     * @return the value of notasxcalifxsoc.id_rubricaxitem
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    public Integer getIdRubricaxitem() {
        return idRubricaxitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notasxcalifxsoc.id_rubricaxitem
     *
     * @param idRubricaxitem the value for notasxcalifxsoc.id_rubricaxitem
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    public void setIdRubricaxitem(Integer idRubricaxitem) {
        this.idRubricaxitem = idRubricaxitem;
    }
}