package com.mybatis.models;

public class Notasxcalifxsoc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notasxcalifxsoc.id_notaxsocializacion
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	private Integer idNotaxsocializacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notasxcalifxsoc.id_califxsoc
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	private Integer idCalifxsoc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notasxcalifxsoc.id_rubricaxitem
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	private Integer idRubricaxitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notasxcalifxsoc.id_estudiante
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	private Integer idEstudiante;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notasxcalifxsoc.id_notaxsocializacion
	 * @return  the value of notasxcalifxsoc.id_notaxsocializacion
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public Integer getIdNotaxsocializacion() {
		return idNotaxsocializacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notasxcalifxsoc.id_notaxsocializacion
	 * @param idNotaxsocializacion  the value for notasxcalifxsoc.id_notaxsocializacion
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public void setIdNotaxsocializacion(Integer idNotaxsocializacion) {
		this.idNotaxsocializacion = idNotaxsocializacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notasxcalifxsoc.id_califxsoc
	 * @return  the value of notasxcalifxsoc.id_califxsoc
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public Integer getIdCalifxsoc() {
		return idCalifxsoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notasxcalifxsoc.id_califxsoc
	 * @param idCalifxsoc  the value for notasxcalifxsoc.id_califxsoc
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public void setIdCalifxsoc(Integer idCalifxsoc) {
		this.idCalifxsoc = idCalifxsoc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notasxcalifxsoc.id_rubricaxitem
	 * @return  the value of notasxcalifxsoc.id_rubricaxitem
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public Integer getIdRubricaxitem() {
		return idRubricaxitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notasxcalifxsoc.id_rubricaxitem
	 * @param idRubricaxitem  the value for notasxcalifxsoc.id_rubricaxitem
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public void setIdRubricaxitem(Integer idRubricaxitem) {
		this.idRubricaxitem = idRubricaxitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notasxcalifxsoc.id_estudiante
	 * @return  the value of notasxcalifxsoc.id_estudiante
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public Integer getIdEstudiante() {
		return idEstudiante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notasxcalifxsoc.id_estudiante
	 * @param idEstudiante  the value for notasxcalifxsoc.id_estudiante
	 * @mbg.generated  Sat Feb 16 16:10:35 COT 2019
	 */
	public void setIdEstudiante(Integer idEstudiante) {
		this.idEstudiante = idEstudiante;
	}
}