package com.mybatis.models;

public class Profesoresxasignaturas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profesoresxasignaturas.id_profxasig
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    private Integer idProfxasig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profesoresxasignaturas.id_profesor
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    private Integer idProfesor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profesoresxasignaturas.id_asignatura
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    private Integer idAsignatura;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profesoresxasignaturas.id_profxasig
     *
     * @return the value of profesoresxasignaturas.id_profxasig
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public Integer getIdProfxasig() {
        return idProfxasig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profesoresxasignaturas.id_profxasig
     *
     * @param idProfxasig the value for profesoresxasignaturas.id_profxasig
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void setIdProfxasig(Integer idProfxasig) {
        this.idProfxasig = idProfxasig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profesoresxasignaturas.id_profesor
     *
     * @return the value of profesoresxasignaturas.id_profesor
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public Integer getIdProfesor() {
        return idProfesor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profesoresxasignaturas.id_profesor
     *
     * @param idProfesor the value for profesoresxasignaturas.id_profesor
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profesoresxasignaturas.id_asignatura
     *
     * @return the value of profesoresxasignaturas.id_asignatura
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public Integer getIdAsignatura() {
        return idAsignatura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profesoresxasignaturas.id_asignatura
     *
     * @param idAsignatura the value for profesoresxasignaturas.id_asignatura
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void setIdAsignatura(Integer idAsignatura) {
        this.idAsignatura = idAsignatura;
    }
}