package com.mybatis.models;

import java.util.ArrayList;
import java.util.List;

public class ProfesoresxasignaturasExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public ProfesoresxasignaturasExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdProfxasigIsNull() {
            addCriterion("id_profxasig is null");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigIsNotNull() {
            addCriterion("id_profxasig is not null");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigEqualTo(Integer value) {
            addCriterion("id_profxasig =", value, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigNotEqualTo(Integer value) {
            addCriterion("id_profxasig <>", value, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigGreaterThan(Integer value) {
            addCriterion("id_profxasig >", value, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_profxasig >=", value, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigLessThan(Integer value) {
            addCriterion("id_profxasig <", value, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigLessThanOrEqualTo(Integer value) {
            addCriterion("id_profxasig <=", value, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigIn(List<Integer> values) {
            addCriterion("id_profxasig in", values, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigNotIn(List<Integer> values) {
            addCriterion("id_profxasig not in", values, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigBetween(Integer value1, Integer value2) {
            addCriterion("id_profxasig between", value1, value2, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfxasigNotBetween(Integer value1, Integer value2) {
            addCriterion("id_profxasig not between", value1, value2, "idProfxasig");
            return (Criteria) this;
        }

        public Criteria andIdProfesorIsNull() {
            addCriterion("id_profesor is null");
            return (Criteria) this;
        }

        public Criteria andIdProfesorIsNotNull() {
            addCriterion("id_profesor is not null");
            return (Criteria) this;
        }

        public Criteria andIdProfesorEqualTo(Integer value) {
            addCriterion("id_profesor =", value, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorNotEqualTo(Integer value) {
            addCriterion("id_profesor <>", value, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorGreaterThan(Integer value) {
            addCriterion("id_profesor >", value, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_profesor >=", value, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorLessThan(Integer value) {
            addCriterion("id_profesor <", value, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorLessThanOrEqualTo(Integer value) {
            addCriterion("id_profesor <=", value, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorIn(List<Integer> values) {
            addCriterion("id_profesor in", values, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorNotIn(List<Integer> values) {
            addCriterion("id_profesor not in", values, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorBetween(Integer value1, Integer value2) {
            addCriterion("id_profesor between", value1, value2, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdProfesorNotBetween(Integer value1, Integer value2) {
            addCriterion("id_profesor not between", value1, value2, "idProfesor");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaIsNull() {
            addCriterion("id_asignatura is null");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaIsNotNull() {
            addCriterion("id_asignatura is not null");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaEqualTo(Integer value) {
            addCriterion("id_asignatura =", value, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaNotEqualTo(Integer value) {
            addCriterion("id_asignatura <>", value, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaGreaterThan(Integer value) {
            addCriterion("id_asignatura >", value, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_asignatura >=", value, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaLessThan(Integer value) {
            addCriterion("id_asignatura <", value, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaLessThanOrEqualTo(Integer value) {
            addCriterion("id_asignatura <=", value, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaIn(List<Integer> values) {
            addCriterion("id_asignatura in", values, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaNotIn(List<Integer> values) {
            addCriterion("id_asignatura not in", values, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaBetween(Integer value1, Integer value2) {
            addCriterion("id_asignatura between", value1, value2, "idAsignatura");
            return (Criteria) this;
        }

        public Criteria andIdAsignaturaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_asignatura not between", value1, value2, "idAsignatura");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 04 00:52:19 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table profesoresxasignaturas
     *
     * @mbg.generated Mon Dec 04 00:52:19 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}