package com.mybatis.models;

public class Rubrica {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubrica.id_rubrica
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    private Integer idRubrica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubrica.id_asignatura
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    private Integer idAsignatura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubrica.descripcion
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubrica.id_tipo_rubrica
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    private Integer idTipoRubrica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubrica.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    private Integer idSocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubrica.numero
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    private Integer numero;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubrica.id_rubrica
     *
     * @return the value of rubrica.id_rubrica
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public Integer getIdRubrica() {
        return idRubrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubrica.id_rubrica
     *
     * @param idRubrica the value for rubrica.id_rubrica
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public void setIdRubrica(Integer idRubrica) {
        this.idRubrica = idRubrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubrica.id_asignatura
     *
     * @return the value of rubrica.id_asignatura
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public Integer getIdAsignatura() {
        return idAsignatura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubrica.id_asignatura
     *
     * @param idAsignatura the value for rubrica.id_asignatura
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public void setIdAsignatura(Integer idAsignatura) {
        this.idAsignatura = idAsignatura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubrica.descripcion
     *
     * @return the value of rubrica.descripcion
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubrica.descripcion
     *
     * @param descripcion the value for rubrica.descripcion
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubrica.id_tipo_rubrica
     *
     * @return the value of rubrica.id_tipo_rubrica
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public Integer getIdTipoRubrica() {
        return idTipoRubrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubrica.id_tipo_rubrica
     *
     * @param idTipoRubrica the value for rubrica.id_tipo_rubrica
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public void setIdTipoRubrica(Integer idTipoRubrica) {
        this.idTipoRubrica = idTipoRubrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubrica.id_socializacion
     *
     * @return the value of rubrica.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public Integer getIdSocializacion() {
        return idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubrica.id_socializacion
     *
     * @param idSocializacion the value for rubrica.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public void setIdSocializacion(Integer idSocializacion) {
        this.idSocializacion = idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubrica.numero
     *
     * @return the value of rubrica.numero
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubrica.numero
     *
     * @param numero the value for rubrica.numero
     *
     * @mbg.generated Mon Mar 26 14:58:32 COT 2018
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
}