package com.mybatis.models;

import java.util.Date;

public class Rubrica {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.id_rubrica
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Integer idRubrica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.id_asignatura
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Integer idAsignatura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.descripcion
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private String descripcion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.id_tipo_rubrica
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Integer idTipoRubrica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.numero
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Integer numero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.version
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.fecha_version
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Date fechaVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rubrica.alcance_nota
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	private Integer alcanceNota;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.id_rubrica
	 * @return  the value of rubrica.id_rubrica
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Integer getIdRubrica() {
		return idRubrica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.id_rubrica
	 * @param idRubrica  the value for rubrica.id_rubrica
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setIdRubrica(Integer idRubrica) {
		this.idRubrica = idRubrica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.id_asignatura
	 * @return  the value of rubrica.id_asignatura
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Integer getIdAsignatura() {
		return idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.id_asignatura
	 * @param idAsignatura  the value for rubrica.id_asignatura
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setIdAsignatura(Integer idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.descripcion
	 * @return  the value of rubrica.descripcion
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.descripcion
	 * @param descripcion  the value for rubrica.descripcion
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.id_tipo_rubrica
	 * @return  the value of rubrica.id_tipo_rubrica
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Integer getIdTipoRubrica() {
		return idTipoRubrica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.id_tipo_rubrica
	 * @param idTipoRubrica  the value for rubrica.id_tipo_rubrica
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setIdTipoRubrica(Integer idTipoRubrica) {
		this.idTipoRubrica = idTipoRubrica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.numero
	 * @return  the value of rubrica.numero
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Integer getNumero() {
		return numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.numero
	 * @param numero  the value for rubrica.numero
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.version
	 * @return  the value of rubrica.version
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.version
	 * @param version  the value for rubrica.version
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.fecha_version
	 * @return  the value of rubrica.fecha_version
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Date getFechaVersion() {
		return fechaVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.fecha_version
	 * @param fechaVersion  the value for rubrica.fecha_version
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setFechaVersion(Date fechaVersion) {
		this.fechaVersion = fechaVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rubrica.alcance_nota
	 * @return  the value of rubrica.alcance_nota
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public Integer getAlcanceNota() {
		return alcanceNota;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rubrica.alcance_nota
	 * @param alcanceNota  the value for rubrica.alcance_nota
	 * @mbg.generated  Sat Feb 16 11:11:26 COT 2019
	 */
	public void setAlcanceNota(Integer alcanceNota) {
		this.alcanceNota = alcanceNota;
	}
}