package com.mybatis.models;

public class Rubricaxitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubricaxitem.id_rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    private Integer idRubricaxitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubricaxitem.id_rubrica
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    private Integer idRubrica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubricaxitem.calificacion
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    private Integer calificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rubricaxitem.descripcion_item
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    private Integer descripcionItem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubricaxitem.id_rubricaxitem
     *
     * @return the value of rubricaxitem.id_rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public Integer getIdRubricaxitem() {
        return idRubricaxitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubricaxitem.id_rubricaxitem
     *
     * @param idRubricaxitem the value for rubricaxitem.id_rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void setIdRubricaxitem(Integer idRubricaxitem) {
        this.idRubricaxitem = idRubricaxitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubricaxitem.id_rubrica
     *
     * @return the value of rubricaxitem.id_rubrica
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public Integer getIdRubrica() {
        return idRubrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubricaxitem.id_rubrica
     *
     * @param idRubrica the value for rubricaxitem.id_rubrica
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void setIdRubrica(Integer idRubrica) {
        this.idRubrica = idRubrica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubricaxitem.calificacion
     *
     * @return the value of rubricaxitem.calificacion
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public Integer getCalificacion() {
        return calificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubricaxitem.calificacion
     *
     * @param calificacion the value for rubricaxitem.calificacion
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rubricaxitem.descripcion_item
     *
     * @return the value of rubricaxitem.descripcion_item
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public Integer getDescripcionItem() {
        return descripcionItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rubricaxitem.descripcion_item
     *
     * @param descripcionItem the value for rubricaxitem.descripcion_item
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void setDescripcionItem(Integer descripcionItem) {
        this.descripcionItem = descripcionItem;
    }
}