package com.mybatis.models;

import java.util.ArrayList;
import java.util.List;

public class RubricaxitemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public RubricaxitemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdRubricaxitemIsNull() {
            addCriterion("id_rubricaxitem is null");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemIsNotNull() {
            addCriterion("id_rubricaxitem is not null");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemEqualTo(Integer value) {
            addCriterion("id_rubricaxitem =", value, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemNotEqualTo(Integer value) {
            addCriterion("id_rubricaxitem <>", value, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemGreaterThan(Integer value) {
            addCriterion("id_rubricaxitem >", value, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_rubricaxitem >=", value, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemLessThan(Integer value) {
            addCriterion("id_rubricaxitem <", value, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemLessThanOrEqualTo(Integer value) {
            addCriterion("id_rubricaxitem <=", value, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemIn(List<Integer> values) {
            addCriterion("id_rubricaxitem in", values, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemNotIn(List<Integer> values) {
            addCriterion("id_rubricaxitem not in", values, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemBetween(Integer value1, Integer value2) {
            addCriterion("id_rubricaxitem between", value1, value2, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaxitemNotBetween(Integer value1, Integer value2) {
            addCriterion("id_rubricaxitem not between", value1, value2, "idRubricaxitem");
            return (Criteria) this;
        }

        public Criteria andIdRubricaIsNull() {
            addCriterion("id_rubrica is null");
            return (Criteria) this;
        }

        public Criteria andIdRubricaIsNotNull() {
            addCriterion("id_rubrica is not null");
            return (Criteria) this;
        }

        public Criteria andIdRubricaEqualTo(Integer value) {
            addCriterion("id_rubrica =", value, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaNotEqualTo(Integer value) {
            addCriterion("id_rubrica <>", value, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaGreaterThan(Integer value) {
            addCriterion("id_rubrica >", value, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_rubrica >=", value, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaLessThan(Integer value) {
            addCriterion("id_rubrica <", value, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaLessThanOrEqualTo(Integer value) {
            addCriterion("id_rubrica <=", value, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaIn(List<Integer> values) {
            addCriterion("id_rubrica in", values, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaNotIn(List<Integer> values) {
            addCriterion("id_rubrica not in", values, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaBetween(Integer value1, Integer value2) {
            addCriterion("id_rubrica between", value1, value2, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andIdRubricaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_rubrica not between", value1, value2, "idRubrica");
            return (Criteria) this;
        }

        public Criteria andCalificacionIsNull() {
            addCriterion("calificacion is null");
            return (Criteria) this;
        }

        public Criteria andCalificacionIsNotNull() {
            addCriterion("calificacion is not null");
            return (Criteria) this;
        }

        public Criteria andCalificacionEqualTo(Integer value) {
            addCriterion("calificacion =", value, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionNotEqualTo(Integer value) {
            addCriterion("calificacion <>", value, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionGreaterThan(Integer value) {
            addCriterion("calificacion >", value, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionGreaterThanOrEqualTo(Integer value) {
            addCriterion("calificacion >=", value, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionLessThan(Integer value) {
            addCriterion("calificacion <", value, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionLessThanOrEqualTo(Integer value) {
            addCriterion("calificacion <=", value, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionIn(List<Integer> values) {
            addCriterion("calificacion in", values, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionNotIn(List<Integer> values) {
            addCriterion("calificacion not in", values, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionBetween(Integer value1, Integer value2) {
            addCriterion("calificacion between", value1, value2, "calificacion");
            return (Criteria) this;
        }

        public Criteria andCalificacionNotBetween(Integer value1, Integer value2) {
            addCriterion("calificacion not between", value1, value2, "calificacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemIsNull() {
            addCriterion("descripcion_item is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemIsNotNull() {
            addCriterion("descripcion_item is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemEqualTo(Integer value) {
            addCriterion("descripcion_item =", value, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemNotEqualTo(Integer value) {
            addCriterion("descripcion_item <>", value, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemGreaterThan(Integer value) {
            addCriterion("descripcion_item >", value, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemGreaterThanOrEqualTo(Integer value) {
            addCriterion("descripcion_item >=", value, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemLessThan(Integer value) {
            addCriterion("descripcion_item <", value, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemLessThanOrEqualTo(Integer value) {
            addCriterion("descripcion_item <=", value, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemIn(List<Integer> values) {
            addCriterion("descripcion_item in", values, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemNotIn(List<Integer> values) {
            addCriterion("descripcion_item not in", values, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemBetween(Integer value1, Integer value2) {
            addCriterion("descripcion_item between", value1, value2, "descripcionItem");
            return (Criteria) this;
        }

        public Criteria andDescripcionItemNotBetween(Integer value1, Integer value2) {
            addCriterion("descripcion_item not between", value1, value2, "descripcionItem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rubricaxitem
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 04 00:52:32 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rubricaxitem
     *
     * @mbg.generated Mon Dec 04 00:52:32 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}