package com.mybatis.models;

public class Salonxprofesores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxprofesores.id_salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    private Integer idSalonxprofesores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxprofesores.id_salon
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    private Integer idSalon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxprofesores.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    private Integer idSocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxprofesores.id_profesor
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    private Integer idProfesor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxprofesores.id_salonxprofesores
     *
     * @return the value of salonxprofesores.id_salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public Integer getIdSalonxprofesores() {
        return idSalonxprofesores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxprofesores.id_salonxprofesores
     *
     * @param idSalonxprofesores the value for salonxprofesores.id_salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public void setIdSalonxprofesores(Integer idSalonxprofesores) {
        this.idSalonxprofesores = idSalonxprofesores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxprofesores.id_salon
     *
     * @return the value of salonxprofesores.id_salon
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public Integer getIdSalon() {
        return idSalon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxprofesores.id_salon
     *
     * @param idSalon the value for salonxprofesores.id_salon
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public void setIdSalon(Integer idSalon) {
        this.idSalon = idSalon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxprofesores.id_socializacion
     *
     * @return the value of salonxprofesores.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public Integer getIdSocializacion() {
        return idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxprofesores.id_socializacion
     *
     * @param idSocializacion the value for salonxprofesores.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public void setIdSocializacion(Integer idSocializacion) {
        this.idSocializacion = idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxprofesores.id_profesor
     *
     * @return the value of salonxprofesores.id_profesor
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public Integer getIdProfesor() {
        return idProfesor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxprofesores.id_profesor
     *
     * @param idProfesor the value for salonxprofesores.id_profesor
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
}