package com.mybatis.models;

public class Salonxequipo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxequipo.id_salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    private Integer idSalonxprofesores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxequipo.id_salon
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    private Integer idSalon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxequipo.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    private Integer idSocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salonxequipo.id_equipo
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    private Integer idEquipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxequipo.id_salonxprofesores
     *
     * @return the value of salonxequipo.id_salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public Integer getIdSalonxprofesores() {
        return idSalonxprofesores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxequipo.id_salonxprofesores
     *
     * @param idSalonxprofesores the value for salonxequipo.id_salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public void setIdSalonxprofesores(Integer idSalonxprofesores) {
        this.idSalonxprofesores = idSalonxprofesores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxequipo.id_salon
     *
     * @return the value of salonxequipo.id_salon
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public Integer getIdSalon() {
        return idSalon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxequipo.id_salon
     *
     * @param idSalon the value for salonxequipo.id_salon
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public void setIdSalon(Integer idSalon) {
        this.idSalon = idSalon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxequipo.id_socializacion
     *
     * @return the value of salonxequipo.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public Integer getIdSocializacion() {
        return idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxequipo.id_socializacion
     *
     * @param idSocializacion the value for salonxequipo.id_socializacion
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public void setIdSocializacion(Integer idSocializacion) {
        this.idSocializacion = idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salonxequipo.id_equipo
     *
     * @return the value of salonxequipo.id_equipo
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public Integer getIdEquipo() {
        return idEquipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salonxequipo.id_equipo
     *
     * @param idEquipo the value for salonxequipo.id_equipo
     *
     * @mbg.generated Mon Mar 26 14:59:28 COT 2018
     */
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
}