package com.mybatis.models;

public class SocializacionAsistencia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socializacion_asistencia.id_soc_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    private Integer idSocAsistencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socializacion_asistencia.id_socializacion
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    private Integer idSocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socializacion_asistencia.id_estudiante
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    private Integer idEstudiante;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socializacion_asistencia.id_soc_asistencia
     *
     * @return the value of socializacion_asistencia.id_soc_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public Integer getIdSocAsistencia() {
        return idSocAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socializacion_asistencia.id_soc_asistencia
     *
     * @param idSocAsistencia the value for socializacion_asistencia.id_soc_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void setIdSocAsistencia(Integer idSocAsistencia) {
        this.idSocAsistencia = idSocAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socializacion_asistencia.id_socializacion
     *
     * @return the value of socializacion_asistencia.id_socializacion
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public Integer getIdSocializacion() {
        return idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socializacion_asistencia.id_socializacion
     *
     * @param idSocializacion the value for socializacion_asistencia.id_socializacion
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void setIdSocializacion(Integer idSocializacion) {
        this.idSocializacion = idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socializacion_asistencia.id_estudiante
     *
     * @return the value of socializacion_asistencia.id_estudiante
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public Integer getIdEstudiante() {
        return idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socializacion_asistencia.id_estudiante
     *
     * @param idEstudiante the value for socializacion_asistencia.id_estudiante
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
}