package com.mybatis.models;

public class Socializacion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socializacion.id_socializacion
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    private Integer idSocializacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socializacion.id_equipo
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    private Integer idEquipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socializacion.id_evento
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    private Integer idEvento;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socializacion.id_socializacion
     *
     * @return the value of socializacion.id_socializacion
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    public Integer getIdSocializacion() {
        return idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socializacion.id_socializacion
     *
     * @param idSocializacion the value for socializacion.id_socializacion
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    public void setIdSocializacion(Integer idSocializacion) {
        this.idSocializacion = idSocializacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socializacion.id_equipo
     *
     * @return the value of socializacion.id_equipo
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    public Integer getIdEquipo() {
        return idEquipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socializacion.id_equipo
     *
     * @param idEquipo the value for socializacion.id_equipo
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socializacion.id_evento
     *
     * @return the value of socializacion.id_evento
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    public Integer getIdEvento() {
        return idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socializacion.id_evento
     *
     * @param idEvento the value for socializacion.id_evento
     *
     * @mbg.generated Mon Mar 26 15:01:09 COT 2018
     */
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }
}