package com.mybatis.models;

import java.util.ArrayList;
import java.util.List;

public class SocializacionAsistenciaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public SocializacionAsistenciaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdSocAsistenciaIsNull() {
            addCriterion("id_soc_asistencia is null");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaIsNotNull() {
            addCriterion("id_soc_asistencia is not null");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaEqualTo(Integer value) {
            addCriterion("id_soc_asistencia =", value, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaNotEqualTo(Integer value) {
            addCriterion("id_soc_asistencia <>", value, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaGreaterThan(Integer value) {
            addCriterion("id_soc_asistencia >", value, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_soc_asistencia >=", value, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaLessThan(Integer value) {
            addCriterion("id_soc_asistencia <", value, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaLessThanOrEqualTo(Integer value) {
            addCriterion("id_soc_asistencia <=", value, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaIn(List<Integer> values) {
            addCriterion("id_soc_asistencia in", values, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaNotIn(List<Integer> values) {
            addCriterion("id_soc_asistencia not in", values, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaBetween(Integer value1, Integer value2) {
            addCriterion("id_soc_asistencia between", value1, value2, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocAsistenciaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_soc_asistencia not between", value1, value2, "idSocAsistencia");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionIsNull() {
            addCriterion("id_socializacion is null");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionIsNotNull() {
            addCriterion("id_socializacion is not null");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionEqualTo(Integer value) {
            addCriterion("id_socializacion =", value, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionNotEqualTo(Integer value) {
            addCriterion("id_socializacion <>", value, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionGreaterThan(Integer value) {
            addCriterion("id_socializacion >", value, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_socializacion >=", value, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionLessThan(Integer value) {
            addCriterion("id_socializacion <", value, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionLessThanOrEqualTo(Integer value) {
            addCriterion("id_socializacion <=", value, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionIn(List<Integer> values) {
            addCriterion("id_socializacion in", values, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionNotIn(List<Integer> values) {
            addCriterion("id_socializacion not in", values, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionBetween(Integer value1, Integer value2) {
            addCriterion("id_socializacion between", value1, value2, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdSocializacionNotBetween(Integer value1, Integer value2) {
            addCriterion("id_socializacion not between", value1, value2, "idSocializacion");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIsNull() {
            addCriterion("id_estudiante is null");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIsNotNull() {
            addCriterion("id_estudiante is not null");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteEqualTo(Integer value) {
            addCriterion("id_estudiante =", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotEqualTo(Integer value) {
            addCriterion("id_estudiante <>", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteGreaterThan(Integer value) {
            addCriterion("id_estudiante >", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_estudiante >=", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteLessThan(Integer value) {
            addCriterion("id_estudiante <", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteLessThanOrEqualTo(Integer value) {
            addCriterion("id_estudiante <=", value, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteIn(List<Integer> values) {
            addCriterion("id_estudiante in", values, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotIn(List<Integer> values) {
            addCriterion("id_estudiante not in", values, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteBetween(Integer value1, Integer value2) {
            addCriterion("id_estudiante between", value1, value2, "idEstudiante");
            return (Criteria) this;
        }

        public Criteria andIdEstudianteNotBetween(Integer value1, Integer value2) {
            addCriterion("id_estudiante not between", value1, value2, "idEstudiante");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 26 15:01:27 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}