package com.mybatis.models;

import java.util.Date;

public class SolicitudAsesoria {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solicitud_asesoria.id_solicitud
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    private Integer idSolicitud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solicitud_asesoria.id_estudiante
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    private Integer idEstudiante;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solicitud_asesoria.dia_semana
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    private Integer diaSemana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solicitud_asesoria.hora_semana
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    private Date horaSemana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solicitud_asesoria.aceptada
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    private Boolean aceptada;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solicitud_asesoria.id_solicitud
     *
     * @return the value of solicitud_asesoria.id_solicitud
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public Integer getIdSolicitud() {
        return idSolicitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solicitud_asesoria.id_solicitud
     *
     * @param idSolicitud the value for solicitud_asesoria.id_solicitud
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solicitud_asesoria.id_estudiante
     *
     * @return the value of solicitud_asesoria.id_estudiante
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public Integer getIdEstudiante() {
        return idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solicitud_asesoria.id_estudiante
     *
     * @param idEstudiante the value for solicitud_asesoria.id_estudiante
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solicitud_asesoria.dia_semana
     *
     * @return the value of solicitud_asesoria.dia_semana
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public Integer getDiaSemana() {
        return diaSemana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solicitud_asesoria.dia_semana
     *
     * @param diaSemana the value for solicitud_asesoria.dia_semana
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public void setDiaSemana(Integer diaSemana) {
        this.diaSemana = diaSemana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solicitud_asesoria.hora_semana
     *
     * @return the value of solicitud_asesoria.hora_semana
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public Date getHoraSemana() {
        return horaSemana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solicitud_asesoria.hora_semana
     *
     * @param horaSemana the value for solicitud_asesoria.hora_semana
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public void setHoraSemana(Date horaSemana) {
        this.horaSemana = horaSemana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solicitud_asesoria.aceptada
     *
     * @return the value of solicitud_asesoria.aceptada
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public Boolean getAceptada() {
        return aceptada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solicitud_asesoria.aceptada
     *
     * @param aceptada the value for solicitud_asesoria.aceptada
     *
     * @mbg.generated Mon Mar 26 15:02:57 COT 2018
     */
    public void setAceptada(Boolean aceptada) {
        this.aceptada = aceptada;
    }
}