package com.mybatis.models;

import java.util.Date;

public class Usuarios {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.id_usuario
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.usuario
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private String usuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.clave
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private String clave;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.nombre
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.apellidos
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private String apellidos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.fecha_nac
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private Date fechaNac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.id_cargo
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private Integer idCargo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.estado
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private Boolean estado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.correo
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private String correo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios.cedula
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	private String cedula;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.id_usuario
	 * @return  the value of usuarios.id_usuario
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.id_usuario
	 * @param idUsuario  the value for usuarios.id_usuario
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.usuario
	 * @return  the value of usuarios.usuario
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public String getUsuario() {
		return usuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.usuario
	 * @param usuario  the value for usuarios.usuario
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.clave
	 * @return  the value of usuarios.clave
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public String getClave() {
		return clave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.clave
	 * @param clave  the value for usuarios.clave
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setClave(String clave) {
		this.clave = clave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.nombre
	 * @return  the value of usuarios.nombre
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.nombre
	 * @param nombre  the value for usuarios.nombre
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.apellidos
	 * @return  the value of usuarios.apellidos
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public String getApellidos() {
		return apellidos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.apellidos
	 * @param apellidos  the value for usuarios.apellidos
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.fecha_nac
	 * @return  the value of usuarios.fecha_nac
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public Date getFechaNac() {
		return fechaNac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.fecha_nac
	 * @param fechaNac  the value for usuarios.fecha_nac
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.id_cargo
	 * @return  the value of usuarios.id_cargo
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public Integer getIdCargo() {
		return idCargo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.id_cargo
	 * @param idCargo  the value for usuarios.id_cargo
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setIdCargo(Integer idCargo) {
		this.idCargo = idCargo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.estado
	 * @return  the value of usuarios.estado
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public Boolean getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.estado
	 * @param estado  the value for usuarios.estado
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.correo
	 * @return  the value of usuarios.correo
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public String getCorreo() {
		return correo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.correo
	 * @param correo  the value for usuarios.correo
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setCorreo(String correo) {
		this.correo = correo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios.cedula
	 * @return  the value of usuarios.cedula
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public String getCedula() {
		return cedula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios.cedula
	 * @param cedula  the value for usuarios.cedula
	 * @mbg.generated  Sun Apr 01 18:04:05 COT 2018
	 */
	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	
}