package com.mybatis.mappers;

import com.mybatis.models.Calificacion;
import com.mybatis.models.CalificacionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalificacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    long countByExample(CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int deleteByExample(CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int deleteByPrimaryKey(Integer idCalificacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int insert(Calificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int insertSelective(Calificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    List<Calificacion> selectByExample(CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    Calificacion selectByPrimaryKey(Integer idCalificacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int updateByExampleSelective(@Param("record") Calificacion record, @Param("example") CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int updateByExample(@Param("record") Calificacion record, @Param("example") CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int updateByPrimaryKeySelective(Calificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbg.generated Mon Mar 26 14:46:53 COT 2018
     */
    int updateByPrimaryKey(Calificacion record);
}