package com.mybatis.mappers;

import com.mybatis.models.Cargo;
import com.mybatis.models.CargoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CargoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	long countByExample(CargoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int deleteByExample(CargoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int deleteByPrimaryKey(Integer idCargo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int insert(Cargo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int insertSelective(Cargo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	List<Cargo> selectByExample(CargoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	Cargo selectByPrimaryKey(Integer idCargo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int updateByExampleSelective(@Param("record") Cargo record, @Param("example") CargoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int updateByExample(@Param("record") Cargo record, @Param("example") CargoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int updateByPrimaryKeySelective(Cargo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo
	 * @mbg.generated  Mon Mar 26 14:55:49 COT 2018
	 */
	int updateByPrimaryKey(Cargo record);
	
	List<Map<String, Object>> getRecords();
}