package com.mybatis.mappers;

import com.mybatis.models.Cargo;
import com.mybatis.models.CargoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CargoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    long countByExample(CargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int deleteByExample(CargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int deleteByPrimaryKey(Integer idCargo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int insert(Cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int insertSelective(Cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    List<Cargo> selectByExample(CargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    Cargo selectByPrimaryKey(Integer idCargo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int updateByExampleSelective(@Param("record") Cargo record, @Param("example") CargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int updateByExample(@Param("record") Cargo record, @Param("example") CargoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int updateByPrimaryKeySelective(Cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbg.generated Mon Dec 04 00:51:18 COT 2017
     */
    int updateByPrimaryKey(Cargo record);
}