package com.mybatis.mappers;

import com.mybatis.models.Estudiantesxequipos;
import com.mybatis.models.EstudiantesxequiposExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstudiantesxequiposMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	long countByExample(EstudiantesxequiposExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int deleteByExample(EstudiantesxequiposExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int deleteByPrimaryKey(Integer idEstxequip);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int insert(Estudiantesxequipos record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int insertSelective(Estudiantesxequipos record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	List<Estudiantesxequipos> selectByExample(EstudiantesxequiposExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	Estudiantesxequipos selectByPrimaryKey(Integer idEstxequip);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int updateByExampleSelective(@Param("record") Estudiantesxequipos record,
			@Param("example") EstudiantesxequiposExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int updateByExample(@Param("record") Estudiantesxequipos record,
			@Param("example") EstudiantesxequiposExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int updateByPrimaryKeySelective(Estudiantesxequipos record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estudiantesxequipos
	 * @mbg.generated  Sun Apr 01 21:23:45 COT 2018
	 */
	int updateByPrimaryKey(Estudiantesxequipos record);
}