package com.mybatis.mappers;

import com.mybatis.models.Notasxcalifxsoc;
import com.mybatis.models.NotasxcalifxsocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotasxcalifxsocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    long countByExample(NotasxcalifxsocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int deleteByExample(NotasxcalifxsocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int deleteByPrimaryKey(Integer idNotaxsocializacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int insert(Notasxcalifxsoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int insertSelective(Notasxcalifxsoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    List<Notasxcalifxsoc> selectByExample(NotasxcalifxsocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    Notasxcalifxsoc selectByPrimaryKey(Integer idNotaxsocializacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int updateByExampleSelective(@Param("record") Notasxcalifxsoc record, @Param("example") NotasxcalifxsocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int updateByExample(@Param("record") Notasxcalifxsoc record, @Param("example") NotasxcalifxsocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int updateByPrimaryKeySelective(Notasxcalifxsoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notasxcalifxsoc
     *
     * @mbg.generated Mon Mar 26 14:57:59 COT 2018
     */
    int updateByPrimaryKey(Notasxcalifxsoc record);
}