package com.mybatis.mappers;

import com.mybatis.models.Rubricaxitem;
import com.mybatis.models.RubricaxitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RubricaxitemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	long countByExample(RubricaxitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int deleteByExample(RubricaxitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int deleteByPrimaryKey(Integer idRubricaxitem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int insert(Rubricaxitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int insertSelective(Rubricaxitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	List<Rubricaxitem> selectByExample(RubricaxitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	Rubricaxitem selectByPrimaryKey(Integer idRubricaxitem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int updateByExampleSelective(@Param("record") Rubricaxitem record, @Param("example") RubricaxitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int updateByExample(@Param("record") Rubricaxitem record, @Param("example") RubricaxitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int updateByPrimaryKeySelective(Rubricaxitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rubricaxitem
	 * @mbg.generated  Sun Jun 10 17:32:07 COT 2018
	 */
	int updateByPrimaryKey(Rubricaxitem record);
}