package com.mybatis.mappers;

import com.mybatis.models.Salon;
import com.mybatis.models.SalonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    long countByExample(SalonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int deleteByExample(SalonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int deleteByPrimaryKey(Integer idSalon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int insert(Salon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int insertSelective(Salon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    List<Salon> selectByExample(SalonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    Salon selectByPrimaryKey(Integer idSalon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int updateByExampleSelective(@Param("record") Salon record, @Param("example") SalonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int updateByExample(@Param("record") Salon record, @Param("example") SalonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int updateByPrimaryKeySelective(Salon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salon
     *
     * @mbg.generated Mon Mar 26 14:59:13 COT 2018
     */
    int updateByPrimaryKey(Salon record);
}