package com.mybatis.mappers;

import com.mybatis.models.Salonxprofesores;
import com.mybatis.models.SalonxprofesoresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalonxprofesoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    long countByExample(SalonxprofesoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int deleteByExample(SalonxprofesoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int deleteByPrimaryKey(Integer idSalonxprofesores);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int insert(Salonxprofesores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int insertSelective(Salonxprofesores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    List<Salonxprofesores> selectByExample(SalonxprofesoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    Salonxprofesores selectByPrimaryKey(Integer idSalonxprofesores);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int updateByExampleSelective(@Param("record") Salonxprofesores record, @Param("example") SalonxprofesoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int updateByExample(@Param("record") Salonxprofesores record, @Param("example") SalonxprofesoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int updateByPrimaryKeySelective(Salonxprofesores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salonxprofesores
     *
     * @mbg.generated Mon Mar 26 14:59:51 COT 2018
     */
    int updateByPrimaryKey(Salonxprofesores record);
}