package com.mybatis.mappers;

import com.mybatis.models.SocializacionAsistencia;
import com.mybatis.models.SocializacionAsistenciaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SocializacionAsistenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    long countByExample(SocializacionAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int deleteByExample(SocializacionAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int deleteByPrimaryKey(Integer idSocAsistencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int insert(SocializacionAsistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int insertSelective(SocializacionAsistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    List<SocializacionAsistencia> selectByExample(SocializacionAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    SocializacionAsistencia selectByPrimaryKey(Integer idSocAsistencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int updateByExampleSelective(@Param("record") SocializacionAsistencia record, @Param("example") SocializacionAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int updateByExample(@Param("record") SocializacionAsistencia record, @Param("example") SocializacionAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int updateByPrimaryKeySelective(SocializacionAsistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socializacion_asistencia
     *
     * @mbg.generated Mon Mar 26 15:01:27 COT 2018
     */
    int updateByPrimaryKey(SocializacionAsistencia record);
}