package com.mybatis.mappers;

import com.mybatis.models.SolicitudAsesoria;
import com.mybatis.models.SolicitudAsesoriaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SolicitudAsesoriaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	long countByExample(SolicitudAsesoriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int deleteByExample(SolicitudAsesoriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int deleteByPrimaryKey(Integer idSolicitud);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int insert(SolicitudAsesoria record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int insertSelective(SolicitudAsesoria record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	List<SolicitudAsesoria> selectByExample(SolicitudAsesoriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	SolicitudAsesoria selectByPrimaryKey(Integer idSolicitud);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int updateByExampleSelective(@Param("record") SolicitudAsesoria record,
			@Param("example") SolicitudAsesoriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int updateByExample(@Param("record") SolicitudAsesoria record, @Param("example") SolicitudAsesoriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int updateByPrimaryKeySelective(SolicitudAsesoria record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solicitud_asesoria
	 * @mbg.generated  Fri Sep 07 15:22:56 COT 2018
	 */
	int updateByPrimaryKey(SolicitudAsesoria record);
}