package com.mybatis.mappers;

import com.mybatis.models.TipoEvento;
import com.mybatis.models.TipoEventoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoEventoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    long countByExample(TipoEventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int deleteByExample(TipoEventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int deleteByPrimaryKey(Integer idTipoEvento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int insert(TipoEvento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int insertSelective(TipoEvento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    List<TipoEvento> selectByExample(TipoEventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    TipoEvento selectByPrimaryKey(Integer idTipoEvento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int updateByExampleSelective(@Param("record") TipoEvento record, @Param("example") TipoEventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int updateByExample(@Param("record") TipoEvento record, @Param("example") TipoEventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int updateByPrimaryKeySelective(TipoEvento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_evento
     *
     * @mbg.generated Mon Mar 26 15:03:33 COT 2018
     */
    int updateByPrimaryKey(TipoEvento record);
}