package com.mybatis.mappers;

import com.mybatis.models.Usuarios;
import com.mybatis.models.UsuariosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface UsuariosMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	long countByExample(UsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int deleteByExample(UsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int deleteByPrimaryKey(Integer idUsuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int insert(Usuarios record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int insertSelective(Usuarios record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	List<Usuarios> selectByExample(UsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	Usuarios selectByPrimaryKey(Integer idUsuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int updateByExampleSelective(@Param("record") Usuarios record, @Param("example") UsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int updateByExample(@Param("record") Usuarios record, @Param("example") UsuariosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int updateByPrimaryKeySelective(Usuarios record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios
	 * @mbg.generated  Sat Jan 26 22:59:39 COT 2019
	 */
	int updateByPrimaryKey(Usuarios record);

	@Select("SELECT EXISTS(SELECT 1 FROM usuarios WHERE cedula=#{cedula})")
	boolean checkUserExists(@Param("cedula") String cedula);
	
	/**
	 * getNextId
	 */
	int getNextId();
}